### ISSUE TITLE
Error when creating new stream account

### ISSUE THREAD

**Issue by hello-world-939** [GetStream/stream-firebase-extensions#8]
I installed the extension but when I create a new firebase account from either the console or from my app no stream account gets created. I looked at the logs for my GCP functions and they return with the following:

Default
2022-05-19T01:38:27.183240Zext-auth-chat-createStreamUserahncqorld5m8 at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:135:23)
Default
2022-05-19T01:38:27.183256Zext-auth-chat-createStreamUserahncqorld5m8 at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:144:25
Default
2022-05-19T01:38:27.183264Zext-auth-chat-createStreamUserahncqorld5m8 at processTicksAndRejections (internal/process/task_queues.js:95:5)
Default
2022-05-19T01:38:27.183557Zext-auth-chat-createStreamUserahncqorld5m8 TypeError: entry.toJSON is not a function
Default
2022-05-19T01:38:27.183567Zext-auth-chat-createStreamUserahncqorld5m8 at /workspace/node_modules/firebase-functions/lib/common/providers/identity.js:113:70
Default
2022-05-19T01:38:27.183573Zext-auth-chat-createStreamUserahncqorld5m8 at Array.map (<anonymous>)
Default
2022-05-19T01:38:27.183580Zext-auth-chat-createStreamUserahncqorld5m8 at Object.record.toJSON (/workspace/node_modules/firebase-functions/lib/common/providers/identity.js:113:49)
Default
2022-05-19T01:38:27.183586Zext-auth-chat-createStreamUserahncqorld5m8 at removeCircular (/workspace/node_modules/firebase-functions/lib/logger/index.js:34:20)
Default
2022-05-19T01:38:27.183592Zext-auth-chat-createStreamUserahncqorld5m8 at write (/workspace/node_modules/firebase-functions/lib/logger/index.js:66:94)
Default
2022-05-19T01:38:27.183597Zext-auth-chat-createStreamUserahncqorld5m8 at Object.log (/workspace/node_modules/firebase-functions/lib/logger/index.js:101:5)
Default
2022-05-19T01:38:27.183602Zext-auth-chat-createStreamUserahncqorld5m8 at /workspace/lib/index.js:11:22
Default
2022-05-19T01:38:27.183608Zext-auth-chat-createStreamUserahncqorld5m8 at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:135:23)
Default
2022-05-19T01:38:27.183616Zext-auth-chat-createStreamUserahncqorld5m8 at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:144:25
Default
2022-05-19T01:38:27.183621Zext-auth-chat-createStreamUserahncqorld5m8 at processTicksAndRejections (internal/process/task_queues.js:95:5)
Debug
2022-05-19T01:38:27.189084311Zext-auth-chat-createStreamUserahncqorld5m8 Function execution took 849 ms, finished with status: 'error'

**Comment by jeevcat** [comment]
Seems this was caused by a bug in the `firebase-functions` dependency. See https://github.com/firebase/firebase-functions/issues/1102

I've updated the dependency and published a new version 010d61893772a0d5a5915cb0cae8962b972ba84e
